spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: gateway-service

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/