server:
  port: 8082
spring:
  application:
    name: "user-service"
  data:
    mongodb:
      host: localhost
      port: 27017
      database: userdb
      username: kalhan
      password: kalhan
      authentication-database: admin

