spring:
  application:
    name: "security-service"
  data:
    mongodb:
      host: localhost
      port: 27017
      database: authdb
      username: kalhan
      password: kalhan
      authentication-database: admin
  mail:
    host: localhost
    port: 1025
    username: kalhan
    password: kalhan
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # 1 day in milliseconds
      refresh-token:
        expiration: 259200000 # 3 days in milliseconds
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  file:
    uploads:
      photos-output-path: ./uploads
server:
  port: 8081

kafka:
  host: localhost:9092
  topics:
    user-registered:
      topicName: auth_service.user_registered.0
      partitionCount: 1
      replicationFactor: 1
      retentionInMs: 604800000
    user-password-reset:
      topicName: auth_service.user_password_reset.0
      partitionCount: 1
      replicationFactor: 1
      retentionInMs: 604800000
